##Comment: Please remove quotes before using it directly as Bash script
"#!/bin/bash",
"SAPProfile=`grep -o 'pf=[^[:space:]]*' /usr/sap/sapservices | grep _HDB`",
"SID=`echo ${SAPProfile} | awk -F \"/\" '{print $4}'`",
"SYSTEMNO=`echo ${SAPProfile} | awk -F \"/\" '{print $7}' | awk -F \"_\" '{print $2}' | sed 's@^[^0-9]*\\([0-9]\\+\\).*@\\1@'`",
"echo  \"Running /usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function GetSystemInstanceList\"",
"/usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function GetSystemInstanceList",
"if [ $? -eq 0 ]",
"then",
"echo \"There is a system here, I am going to use stop\"",
"/usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function StopWait 600 2",
"else",
"echo \"There is no service running for instance number ${SYSTEMNO} \"",
"exit 1",
"fi",
"/usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function GetProcessList",
"if [ $? -eq 4 ]",
"        then",
"           echo \"`date +%F\\ %T`: The HANA Database Stopped Successfully\"",
"        else",
"        echo \"The return code was $? \"",
"           exit 1",
"        fi"
          