##Comment: Please remove quotes before using it directly as Bash script
"#!/bin/bash",
"SAPProfile=`grep -o 'pf=[^[:space:]]*' /usr/sap/sapservices | grep _D`",
"SID=`echo ${SAPProfile} | awk -F \"/\" '{print $4}'`",
"SYSTEMNO=`echo ${SAPProfile} | awk -F \"/\" '{print $7}' | awk -F \"_\" '{print $2}' | sed 's@^[^0-9]*\\([0-9]\\+\\).*@\\1@'`",
"echo \"Running command:\"",
"echo \"/usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function GetSystemInstanceList\"",
"/usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function GetSystemInstanceList",
"        if [ $? -eq 0 ]",
"        then",
"           echo \"There is a system here, I am going to use stop\"",
"           /usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function StopWait 300 2",
"        else",
"           echo \"There is no service running for instance number ${SYSTEMNO} \"",
"exit 1",
"fi",
"echo \"*** Checking that it stopped successfully\"",
"echo \"Running command:\"",
"echo \"/usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function GetProcessList\"",
"/usr/sap/hostctrl/exe/sapcontrol -nr ${SYSTEMNO} -function GetProcessList",
"if [ $? -eq 4 ]",
"        then",
"           echo \"`date +%F\\ %T`: The application stopped successfully\"",
"        else",
"        echo \"The return code was $? \"",
"           exit 1",
"        fi"